services:
  - type: web
    name: navisync-backend
    env: python
    region: singapore
    plan: free
    rootDir: idr_prototype/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
